### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by supersven** [alexbiehl/testcontainers-hs#10]
https://hackage.haskell.org/package/testcontainers-0.3.0.0/docs/TestContainers-Docker.html#v:waitForLogLine

```
wairForLogLine Stdout ("Ready to accept connections" `isInfixOf`)
```

I think this should be `waitForLogLine` (`t` instead of `r`). 😺

**Comment by supersven** [comment]
Ah, what I forgot: Thanks a lot for crafting this library! It helps a lot with creating e.g. integration tests.

**Comment by alexbiehl** [comment]
Thanks for reporting, Sven. Fixed on master!
