### ISSUE TITLE
waitForLine exception

### ISSUE THREAD

**Issue by blackheaven** [alexbiehl/testcontainers-hs#2]
Following (the discussion)[https://github.com/alexbiehl/testcontainers-hs/pull/1#issuecomment-669820253] in #1 (I have tried it)[https://github.com/blackheaven/amqp-streamly/commit/a22392e91a1038ed108d4cc2a25c374f9fafcd3c]:

```
  container <- run $ containerRequest (fromTag "rabbitmq:3.8.4")
    & setWaitingFor (waitForLogLine Stdout (" completed with " `TL.isInfixOf`))
  liftIO $ mkChannel login password $ T.unpack $ containerIp container
```

But I have got this error:

```
  test/Network/AMQP/StreamlySpec.hs:30:7: 
  1) Network.AMQP.Streamly producing 5 messages should be consumed in the right order
       uncaught exception: UnexpectedEndOfPipe
       UnexpectedEndOfPipe {id = "0d93a0e143e11919dc90cd72b7fefa10c92fa8c33ff9c47c373a8c63f30eff0e"}
```

Can you have a look?

**Comment by alexbiehl** [comment]
Ah, yeah, found it. It was a missing `--follow` in the underlying `docker logs` subprocess.

**Comment by alexbiehl** [comment]
I pushed a fix to master

**Comment by blackheaven** [comment]
it works, thanks.
